name: Benachrichtigung über Release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Sende E-Mail
        run: echo "Das hat geklappt"
