name: Benachrichtigung über Release

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Sende E-Mail
        run: echo "Das hat geklappt"
